/*
 * Hometer
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"hometer-server/store"
	"log"
	"net/http"

	"periph.io/x/periph/host"
)

func main() {
	log.Printf("Server started")

	// Load all the drivers:
	if _, err := host.Init(); err != nil {
		log.Fatal(err)
	}

	// Start logging
	go store.StartLoggingValues()

	router := NewRouter()

	log.Fatal(http.ListenAndServe(":9500", router))
}
